name = "tsundoku-dragon"
compatibility_date = "2025-12-23"

[assets]
directory = "./dist"

# ============================================================
# Staging 環境
# ============================================================
[env.staging]
name = "tsundoku-dragon-staging"

# ============================================================
# Production 環境
# ============================================================
[env.production]
name = "tsundoku-dragon"
